# Generated by Django 6.0.7 on 2026-07-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='', max_length=30)),
                ('description', models.TextField(blank=True, default='', max_length=150)),
                ('thumbnail_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
