# Generated by Django 6.0.7 on 2026-08-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videomodel',
            old_name='titel',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='description',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
    ]
