# Generated by Django 6.1 on 2026-08-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='titel',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='description',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
    ]
