# Generated by Django 6.0.7 on 2026-07-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
