# Generated by Django 6.1 on 2026-08-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_rename_titel_videomodel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='description',
            field=models.TextField(default='', max_length=350),
        ),
    ]
