# Generated by Django 6.0.7 on 2026-07-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_videomodel_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
