# Generated by Django 6.0.7 on 2026-08-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_alter_videomodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video_file',
            field=models.FileField(default='', upload_to='videos/'),
        ),
    ]
