# Generated by Django 6.0.7 on 2026-07-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_alter_videomodel_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videomodel',
            old_name='titel',
            new_name='title',
        ),
    ]
