# Generated by Django 6.0.7 on 2026-08-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_alter_videomodel_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
