# Generated by Django 6.0.7 on 2026-07-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_rename_titel_videomodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='description',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
    ]
