# Generated by Django 6.1 on 2026-08-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_alter_videomodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
