# Generated by Django 6.0.7 on 2026-08-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_alter_videomodel_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='thumbnail_url',
            field=models.ImageField(default='', upload_to='thumbnails/'),
        ),
    ]
