# Generated by Django 6.1 on 2026-08-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0006_remove_videomodel_thumbnail_url_videomodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='description',
            field=models.TextField(default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
