# Generated by Django 6.1 on 2026-08-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0008_alter_videomodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='description',
            field=models.TextField(default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
